from __future__ import annotations

from dataclasses import dataclass
from i2sar.core.enums import StrEnum
from pathlib import Path
from typing import Dict, Any, Optional, Tuple, List

import numpy as np
import subprocess
import shutil
import tempfile


class CostMode(StrEnum):
    DEFO = "defo"
    TOPO = "topo"
    SMOOTH = "smooth"


class InitMethod(StrEnum):
    MST = "mst"
    MCF = "mcf"


@dataclass(frozen=True)
class UnwrapResult:
    unwrapped_phase: np.ndarray
    coherence: np.ndarray
    method: str


def _ensure_snaphu_binary(snaphu_bin: str = "snaphu") -> str:
    exe = shutil.which(snaphu_bin)
    if exe is None:
        raise FileNotFoundError(
            f"未找到 snaphu 可执行文件: {snaphu_bin}. "
            "请确认已安装 snaphu 并在 PATH 中可见。"
        )
    return exe


def _sanitize_inputs(
    wrapped_phase: np.ndarray,
    coherence: np.ndarray,
    corr_thresh: Optional[float],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    wrapped_phase = np.asarray(wrapped_phase, dtype=np.float64)
    coherence = np.asarray(coherence, dtype=np.float64)
    
    if wrapped_phase.ndim != 2:
        raise ValueError(f"wrapped_phase 必须为二维数组，当前 shape={wrapped_phase.shape}")
    if coherence.ndim != 2:
        raise ValueError(f"coherence 必须为二维数组，当前 shape={coherence.shape}")
    if wrapped_phase.shape != coherence.shape:
        raise ValueError(
            f"wrapped_phase 与 coherence 形状不一致: {wrapped_phase.shape} vs {coherence.shape}"
        )

    coh = np.where(np.isfinite(coherence), coherence, 0.0)
    coh = np.clip(coh, 0.0, 1.0)

    valid = np.isfinite(wrapped_phase) & np.isfinite(coherence)
    if corr_thresh is not None:
        thr = float(corr_thresh)
        if thr < 0.0 or thr > 1.0:
            raise ValueError(f"corr_thresh 必须在 [0,1]，当前={corr_thresh}")
        valid = valid & (coh >= thr)
        coh = np.where(coh >= thr, coh, 0.0)

    phase = np.where(np.isfinite(wrapped_phase), wrapped_phase, 0.0)
    phase = np.mod(phase, 2.0 * np.pi)
    phase = np.where(valid, phase, 0.0)

    mask = valid.astype(np.uint8)
    if int(mask.sum()) <= 0:
        raise ValueError("所有像素都被掩膜，无法执行 snaphu 解缠。")

    return phase, coh, mask


def _cost_flag(cost_mode: CostMode) -> str:
    m = cost_mode.lower()
    if m == "topo":
        return "-t"
    if m == "defo":
        return "-d"
    if m == "smooth":
        return "-s"
    raise ValueError(f"不支持的 cost_mode: {cost_mode}")


def _init_flag(init_method: InitMethod) -> str:
    m = init_method.lower()
    if m == "mst":
        return "--mst"
    if m == "mcf":
        return "--mcf"
    raise ValueError(f"不支持的 init_method: {init_method}")


class SnaphuUnwrapper:
    def __init__(
        self,
        snaphu_bin: str = "snaphu",
        cost_mode: CostMode = CostMode.DEFO,
        init_method: InitMethod = InitMethod.MST,
        corr_thresh: Optional[float] = None,
        keep_temp: bool = False,
        tile_rows: Optional[int] = None,
        tile_cols: Optional[int] = None,
        tile_row_overlap: int = 512,
        tile_col_overlap: int = 512,
        nproc: Optional[int] = None,
    ):
        self.snaphu_bin = snaphu_bin
        self.cost_mode = cost_mode
        self.init_method = init_method
        self.corr_thresh = corr_thresh
        self.keep_temp = keep_temp
        self.tile_rows = tile_rows
        self.tile_cols = tile_cols
        self.tile_row_overlap = tile_row_overlap
        self.tile_col_overlap = tile_col_overlap
        self.nproc = nproc

    def unwrap(
        self,
        wrapped_phase: np.ndarray,
        coherence: np.ndarray,
    ) -> UnwrapResult:
        exe = _ensure_snaphu_binary(self.snaphu_bin)
        
        phase, coh, mask = _sanitize_inputs(
            wrapped_phase=wrapped_phase,
            coherence=coherence,
            corr_thresh=self.corr_thresh,
        )
        
        h, w = phase.shape
        
        if self.keep_temp:
            tmp_dir = Path(tempfile.mkdtemp(prefix="i2sar_snaphu_tmp_"))
        else:
            tmp_ctx = tempfile.TemporaryDirectory(prefix="i2sar_snaphu_tmp_")
            tmp_dir = Path(tmp_ctx.name)
        
        try:
            wrapped_file = tmp_dir / "wrapped_phase.bin"
            corr_file = tmp_dir / "coherence.bin"
            mask_file = tmp_dir / "mask.bin"
            config_file = tmp_dir / "snaphu.conf"
            out_unw = tmp_dir / "unwrapped_phase.bin"
            
            phase.astype(np.float32).tofile(wrapped_file)
            coh.astype(np.float32).tofile(corr_file)
            mask.astype(np.uint8).tofile(mask_file)
            
            lines = [
                "# Auto-generated by i2sar",
                "INFILEFORMAT FLOAT_DATA",
                "CORRFILEFORMAT FLOAT_DATA",
                "OUTFILEFORMAT FLOAT_DATA",
                f"STATCOSTMODE {self.cost_mode.upper()}",
                f"INITMETHOD {self.init_method.upper()}",
                "VERBOSE TRUE",
                f"RMTMPTILE {'FALSE' if self.keep_temp else 'TRUE'}",
            ]
            config_file.write_text("\n".join(lines) + "\n")
            
            cmd = [
                exe,
                str(wrapped_file),
                str(w),
                "-o",
                str(out_unw),
                "-c",
                str(corr_file),
                "-f",
                str(config_file),
                _cost_flag(self.cost_mode),
                _init_flag(self.init_method),
                "-M", str(mask_file),
            ]
            
            if self.tile_rows is not None and self.tile_cols is not None:
                cmd.extend([
                    "--tile",
                    str(self.tile_rows),
                    str(self.tile_cols),
                    str(self.tile_row_overlap),
                    str(self.tile_col_overlap),
                    "--tiledir",
                    str(tmp_dir / "tiles"),
                ])
                if self.nproc is not None and int(self.nproc) > 0:
                    cmd.extend(["--nproc", str(int(self.nproc))])
            
            with open(tmp_dir / "snaphu.log", "w") as logf:
                proc = subprocess.run(
                    cmd,
                    stdout=logf,
                    stderr=subprocess.STDOUT,
                    text=True,
                    check=True,
                    start_new_session=True,
                )
            
            unwrapped = np.fromfile(out_unw, dtype=np.float32).reshape(h, w)
            
            return UnwrapResult(
                unwrapped_phase=unwrapped,
                coherence=coh,
                method="snaphu",
            )
        finally:
            if not self.keep_temp and tmp_ctx is not None:
                tmp_ctx.cleanup()


def unwrap_snaphu(
    wrapped_phase: np.ndarray,
    coherence: np.ndarray,
    snaphu_bin: str = "snaphu",
    cost_mode: str = "defo",
    init_method: str = "mst",
    corr_thresh: Optional[float] = None,
    keep_temp: bool = False,
    tile_rows: Optional[int] = None,
    tile_cols: Optional[int] = None,
    tile_row_overlap: int = 512,
    tile_col_overlap: int = 512,
    nproc: Optional[int] = None,
) -> Dict[str, Any]:
    cost_mode_enum = CostMode(cost_mode.lower())
    init_method_enum = InitMethod(init_method.lower())
    
    unwrapper = SnaphuUnwrapper(
        snaphu_bin=snaphu_bin,
        cost_mode=cost_mode_enum,
        init_method=init_method_enum,
        corr_thresh=corr_thresh,
        keep_temp=keep_temp,
        tile_rows=tile_rows,
        tile_cols=tile_cols,
        tile_row_overlap=tile_row_overlap,
        tile_col_overlap=tile_col_overlap,
        nproc=nproc,
    )
    
    result = unwrapper.unwrap(wrapped_phase, coherence)
    
    return {
        "unwrapped_phase": result.unwrapped_phase,
        "coherence": result.coherence,
        "method": "snaphu",
        "cost_mode": cost_mode,
        "init_method": init_method,
    }
